# Generated by Django 4.1.5 on 2023-01-25 10:41

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(storage=django.core.files.storage.FileSystemStorage(pathlib.PureWindowsPath('E:/Image Resize/ImageResizerTool/uploads')), upload_to='')),
            ],
            options={
                'unique_together': {('pic',)},
            },
        ),
    ]
