# Generated by Django 4.1.5 on 2023-01-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResizerTool', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
