# Generated by Django 4.1.5 on 2023-01-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResizerTool', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upload',
            unique_together=set(),
        ),
    ]
