# Generated by Django 4.1.5 on 2023-01-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResizerTool', '0004_alter_upload_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
